<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TRADES" nsURI="dsm.TRADES" nsPrefix="TRADES">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TRADES model, by Israel Aerospace Industries. All rights reserved.&#xD;&#xA;&#xD;&#xA;The TRADES model, based on Threat and Risk assessment ontology and the TRADES model-based methodology."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Analysis" eSuperTypes="#//ComponentOwner #//DataOwnerElement #//NamedElement #//AbstractControlOwner #//AbstractThreatOwner">
    <eOperations name="getExternalThreats" upperBound="-1" eType="#//ExternalThreat">
      <eParameters name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="source" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoreSystem" eType="#//ScoreSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkTypes" upperBound="-1"
        eType="#//LinkType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Threat" eSuperTypes="#//NamedElement #//IThreatDefinition">
    <eOperations name="checkIsUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatAllocations" upperBound="-1"
        eType="#//ThreatAllocationRelation" eOpposite="#//ThreatAllocationRelation/threat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threatType" eType="#//threatTypeENUM"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ComponentOwner #//DataOwnerElement #//NamedElement #//AbstractControlOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatAllocations" upperBound="-1"
        eType="#//ThreatAllocationRelation" containment="true" eOpposite="#//ThreatAllocationRelation/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectRelations" upperBound="-1"
        eType="#//AffectRelation" containment="true" eOpposite="#//AffectRelation/sourceComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="#//NamedElement #//IControlDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigatedThreats" upperBound="-1"
        eType="#//Threat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigationRelations" upperBound="-1"
        eType="#//ThreatMitigationRelation" containment="true" eOpposite="#//ThreatMitigationRelation/control"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//ControlStatusENUM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatAllocationRelation">
    <eOperations name="checkComputedDifficultyConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check that the define difference for this allocation is not different from the one computed on the attack chain"/>
      </eAnnotations>
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assessment" lowerBound="1"
        eType="#//AssessmentENUM" defaultValueLiteral="Undecided"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/threatAllocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threat" lowerBound="1"
        eType="#//Threat" eOpposite="#//Threat/threatAllocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impactScore" eType="#//ImpactScore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difficultyScore" eType="#//DifficultyScore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackChain" eType="#//AttackChain"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssessmentENUM">
    <eLiterals name="Undecided"/>
    <eLiterals name="Gap" value="1"/>
    <eLiterals name="Accepted" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatMitigationRelation" eSuperTypes="#//IMitigationLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assessment" lowerBound="1"
        eType="#//AssessmentENUM" defaultValueLiteral="Undecided"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" lowerBound="1"
        eType="#//Control" eOpposite="#//Control/mitigationRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threat" eType="#//Threat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigatedAllocation" eType="#//ThreatAllocationRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AffectRelation" eSuperTypes="#//NamedElement">
    <eOperations name="checkDataScope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check that the referenced data belong to correct scope."/>
      </eAnnotations>
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceComponent" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/affectRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetComponent" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisStatus" lowerBound="1"
        eType="#//AffectedENUM" defaultValueLiteral="Confirmed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AffectedENUM">
    <eLiterals name="Undecided"/>
    <eLiterals name="Confirmed" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="threatTypeENUM">
    <eLiterals name="ConcreteThreat"/>
    <eLiterals name="ConceptualThreat" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackChain" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackchainSteps" upperBound="-1"
        eType="#//AttackChainStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computedDifficulty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackChainStep">
    <eOperations name="getThreatAllocationRelationCandidates" upperBound="-1" eType="#//ThreatAllocationRelation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check that the actual threatAllocationRelation belong to the correct candidates scope."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="checkAllocationValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatAllocationRelation"
        eType="#//ThreatAllocationRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//AttackChainStep"
        eOpposite="#//AttackChainStep/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" upperBound="-1"
        eType="#//AttackChainStep" eOpposite="#//AttackChainStep/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScoreSystem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="impactScores" upperBound="-1"
        eType="#//ImpactScore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difficultyScores" upperBound="-1"
        eType="#//DifficultyScore" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactScore" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//ImpactConfiguration" containment="true" eOpposite="#//ImpactConfiguration/impact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifficultyScore" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOwnerElement" abstract="true">
    <eOperations name="getDatas" upperBound="-1" eType="#//Data"/>
    <eOperations name="getInheritedDatas" upperBound="-1" eType="#//Data"/>
    <eOperations name="getAllDatas" upperBound="-1" eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataOwner" eType="#//DataOwner"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentOwner" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalThreat" eSuperTypes="#//Threat #//ExternalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactConfiguration" eSuperTypes="#//ColoredElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difficulty" lowerBound="1"
        eType="#//DifficultyScore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impact" lowerBound="1"
        eType="#//ImpactScore" eOpposite="#//ImpactScore/configurations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RGBColor" instanceClassName="dsm.TRADES.RGBColor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalControl" eSuperTypes="#//ExternalElement #//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatsOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internals" upperBound="-1"
        eType="#//Threat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externals" upperBound="-1"
        eType="#//ExternalThreat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internals" upperBound="-1"
        eType="#//Control" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externals" upperBound="-1"
        eType="#//ExternalControl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractControlOwner" abstract="true">
    <eOperations name="getAllControls" upperBound="-1" eType="#//Control"/>
    <eOperations name="getExternalControls" upperBound="-1" eType="#//ExternalControl">
      <eParameters name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
      <eParameters name="source" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlOwner" eType="#//ControlOwner"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ControlStatusENUM">
    <eLiterals name="Proposed"/>
    <eLiterals name="Agreed" value="1"/>
    <eLiterals name="Implemented" value="2"/>
    <eLiterals name="Rejected" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkType" lowerBound="1"
        eType="#//LinkType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkConveyed" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/conveyingLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conveyingLink" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/linkConveyed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkType" eSuperTypes="#//NamedElement #//ColoredElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Catalog" eSuperTypes="#//AbstractThreatOwner #//AbstractControlOwner #//NamedElement #//ICatalogDefinition"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractThreatOwner" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatOwner" lowerBound="1"
        eType="#//ThreatsOwner" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IThreatDefinition" abstract="true" interface="true">
    <eOperations name="getId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getDescription" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IControlDefinition" abstract="true"
      interface="true">
    <eOperations name="getDescription" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getMitigatedThreatDefinitions" upperBound="-1" eType="#//IMitigationLink"/>
    <eOperations name="getName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ICatalogDefinition" abstract="true"
      interface="true">
    <eOperations name="getThreatById" eType="#//IThreatDefinition">
      <eParameters name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="getControlById" eType="#//IControlDefinition">
      <eParameters name="id" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eOperations name="getThreatDefinitions" upperBound="-1" eType="#//IThreatDefinition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get all the threat definition (with valid id) contained by this catalog definition"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getControlDefinitions" upperBound="-1" eType="#//IControlDefinition">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Get all the control definition (with valid id) contained by this catalog definition"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getIdentifier" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMitigationLink" abstract="true" interface="true">
    <eOperations name="getDescription" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="getThreat" eType="#//IThreatDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColoredElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//RGBColor"
        defaultValueLiteral="#AAAAAA"/>
  </eClassifiers>
</ecore:EPackage>
