<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TRADES" nsURI="dsm.TRADES" nsPrefix="TRADES">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="TRADES model, by Israel Aerospace Industries. All rights reserved.&#xD;&#xA;&#xD;&#xA;The TRADES model, based on Threat and Risk assessment ontology and the TRADES model-based methodology."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Analysis" eSuperTypes="#//ComponentOwner #//DataOwnerElement #//NamedElement #//AbstractControlOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scoresystem" eType="#//ScoreSystem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatOwner" lowerBound="1"
        eType="#//ThreatsOwner" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Threat" eSuperTypes="#//NamedElement">
    <eOperations name="checkIsUsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocated" upperBound="-1"
        eType="#//Component" eOpposite="#//Component/allocatedThreat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatallocation" upperBound="-1"
        eType="#//ThreatAllocationRelation" eOpposite="#//ThreatAllocationRelation/threat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threatType" eType="#//threatTypeENUM"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Applicability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ComponentOwner #//DataOwnerElement #//NamedElement #//AbstractControlOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedThreat" upperBound="-1"
        eType="#//Threat" eOpposite="#//Threat/allocated"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" upperBound="-1"
        eType="#//Control" eOpposite="#//Control/implementedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatAllocations" upperBound="-1"
        eType="#//ThreatAllocationRelation" containment="true" eOpposite="#//ThreatAllocationRelation/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectrelation" upperBound="-1"
        eType="#//AffectRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threat" upperBound="-1"
        eType="#//Threat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigates" upperBound="-1"
        eType="#//Threat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedBy" upperBound="-1"
        eType="#//Component" eOpposite="#//Component/implements"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigationrRelations" upperBound="-1"
        eType="#//ThreatMitigationRelation" containment="true" eOpposite="#//ThreatMitigationRelation/control"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatAllocationRelation">
    <eOperations name="checkComputedDifficultyConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check that the define difference for this allocation is not different from the one computed on the attack chain"/>
      </eAnnotations>
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assessment" lowerBound="1"
        eType="#//AssessmentENUM" defaultValueLiteral="Undecided"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/threatAllocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threat" lowerBound="1"
        eType="#//Threat" eOpposite="#//Threat/threatallocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impactscore" eType="#//ImpactScore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difficultyscore" eType="#//DifficultyScore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatRelated" upperBound="-1"
        eType="#//ThreatAllocationRelation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackChain" eType="#//AttackChain"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AssessmentENUM">
    <eLiterals name="Undecided"/>
    <eLiterals name="Gap" value="1"/>
    <eLiterals name="Accepted" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatMitigationRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assessment" lowerBound="1"
        eType="#//AssessmentENUM" defaultValueLiteral="Undecided"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="control" lowerBound="1"
        eType="#//Control" eOpposite="#//Control/mitigationrRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threat" eType="#//Threat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mitigates" eType="#//ThreatAllocationRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AffectRelation" eSuperTypes="#//NamedElement">
    <eOperations name="checkDataScope" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check that the referenced data belong to correct scope."/>
      </eAnnotations>
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceComponent" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetComponent" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analysisStatus" lowerBound="1"
        eType="#//AffectedENUM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AffectedENUM">
    <eLiterals name="Undecided"/>
    <eLiterals name="Confirmed" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="threatTypeENUM">
    <eLiterals name="ConcreteThreat"/>
    <eLiterals name="ConceptualThreat" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackChain" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attackchainSteps" upperBound="-1"
        eType="#//AttackChainStep" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="computedDifficulty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackChainStep">
    <eOperations name="getThreatAllocationRelationCandidates" upperBound="-1" eType="#//ThreatAllocationRelation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check that the actual threatAllocationRelation belong to the correct candidates scope."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="checkAllocationValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threatAllocationRelation"
        eType="#//ThreatAllocationRelation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" upperBound="-1" eType="#//AttackChainStep"
        eOpposite="#//AttackChainStep/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" upperBound="-1"
        eType="#//AttackChainStep" eOpposite="#//AttackChainStep/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScoreSystem" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="impactscore" upperBound="-1"
        eType="#//ImpactScore" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difficultyscore" upperBound="-1"
        eType="#//DifficultyScore" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactScore" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurations" upperBound="-1"
        eType="#//ImpactConfiguration" containment="true" eOpposite="#//ImpactConfiguration/impact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DifficultyScore" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOwnerElement" abstract="true">
    <eOperations name="getDatas" upperBound="-1" eType="#//Data"/>
    <eOperations name="getInheritedDatas" upperBound="-1" eType="#//Data"/>
    <eOperations name="getAllDatas" upperBound="-1" eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataOwner" eType="#//DataOwner"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentOwner" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalThreat" eSuperTypes="#//Threat #//ExternalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpactConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="difficulty" lowerBound="1"
        eType="#//DifficultyScore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impact" lowerBound="1"
        eType="#//ImpactScore" eOpposite="#//ImpactScore/configurations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//RGBColor"
        defaultValueLiteral="#FFFFFF"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="RGBColor" instanceClassName="dsm.TRADES.RGBColor"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalControl" eSuperTypes="#//ExternalElement #//Control"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThreatsOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internals" upperBound="-1"
        eType="#//Threat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externals" upperBound="-1"
        eType="#//Threat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internals" upperBound="-1"
        eType="#//Control" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externals" upperBound="-1"
        eType="#//Control" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractControlOwner" abstract="true">
    <eOperations name="getAllControls" upperBound="-1" eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlOwner" eType="#//ControlOwner"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOwner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
