<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PropertiesMarkupWidgets" nsURI="http://www.eclipse.org/sirius/properties/1.0.0/ext/widgets/markupWidgets"
    nsPrefix="PropertiesMarkupWidgets">
  <eClassifiers xsi:type="ecore:EClass" name="ExtHTMLRendererDescription" eSuperTypes="../../org.eclipse.sirius.properties/model/properties.ecore#//WidgetDescription ../../org.eclipse.sirius.properties/model/properties.ecore#//AbstractWidgetDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toHtmlExpression" eType="ecore:EDataType ../../org.eclipse.sirius/model/viewpoint.ecore#//description/InterpretedExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueExpression" eType="ecore:EDataType ../../org.eclipse.sirius/model/viewpoint.ecore#//description/InterpretedExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLines" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialOperation" eType="ecore:EClass ../../org.eclipse.sirius/model/viewpoint.ecore#//description/tool/InitialOperation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editionToolExpression"
        eType="ecore:EDataType ../../org.eclipse.sirius/model/viewpoint.ecore#//description/InterpretedExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cssExpression" eType="ecore:EDataType ../../org.eclipse.sirius/model/viewpoint.ecore#//description/InterpretedExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtMarkdownDescription" eSuperTypes="../../org.eclipse.sirius.properties/model/properties.ecore#//WidgetDescription ../../org.eclipse.sirius.properties/model/properties.ecore#//AbstractWidgetDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueExpression" eType="ecore:EDataType ../../org.eclipse.sirius/model/viewpoint.ecore#//description/InterpretedExpression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLines" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialOperation" eType="ecore:EClass ../../org.eclipse.sirius/model/viewpoint.ecore#//description/tool/InitialOperation"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
