<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extTRADES" nsURI="http://www.example.org/extTRADES" nsPrefix="extTRADES">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Extension to TRADES model for external sources, by Israel Aerospace Industries. All rights reserved.&#xD;&#xA;&#xD;&#xA;This is an extension to the TRADES model, in order to support and represent elements from an external database.&#xD;&#xA;Specifically, Threat and Control are supported. The model adds the identification of the external source for the element, as well as a link to a resource representing/explaining the element."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="extThreat" eSuperTypes="../../dsm.TRADES/model/TRADES.ecore#//Threat #//extElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="extElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="link" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtControl" eSuperTypes="../../dsm.TRADES/model/TRADES.ecore#//Control #//extElement"/>
</ecore:EPackage>
