/**
 * Copyright (c) Israel Aerospace Industries, Eclipse contributors and others 2021.
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *    Israel Aerospace Industries - initial API and implementation
 */

package org.eclipse.eef.ide.ui.ext.widgets.markup.internal.markdown;

import static java.util.stream.Collectors.toList;

import java.util.Collections;
import java.util.List;

import org.eclipse.swt.custom.StyleRange;

/**
 * Describes a list of coherent {@link StyleRange} and {@link LineBackground}.
 *
 * @author Arthur Daussy
 *
 */
public class StyleDescription {

	/**
	 * A empty style description.
	 */
	public static final StyleDescription EMPTY = new StyleDescription(Collections.emptyList(), Collections.emptyList());

	/**
	 * Styles.
	 */
	private final List<StyleRange> styles;

	/**
	 * Line backgrounds.
	 */
	private final List<LineBackground> lineBackgrounds;

	/**
	 * Simple constructor.
	 *
	 * @param styles
	 *            list of style to be applied
	 * @param lineBackgrounds
	 *            list of back color to be applied
	 */
	public StyleDescription(List<StyleRange> styles, List<LineBackground> lineBackgrounds) {
		super();
		this.styles = styles;
		this.lineBackgrounds = lineBackgrounds;
	}

	public List<StyleRange> getStyles() {
		return styles;
	}

	/**
	 * Filter out all styles that can't be applied to the given text.
	 *
	 * @param text
	 *            a value (not null)
	 * @return a new {@link StyleDescription}
	 */
	public StyleDescription filterWithText(String text) {

		if (text == null) {
			return EMPTY;
		}

		long nbLine = text.lines().count();

		int length = text.length();
		List<StyleRange> filteredStyle = styles.stream().filter(sr -> {
			return sr.length + sr.start <= length;
		}).collect(toList());

		List<LineBackground> filteredLineBackground = lineBackgrounds.stream().filter(lb -> lb.getEndLine() < nbLine).collect(toList());

		return new StyleDescription(filteredStyle, filteredLineBackground);

	}

	public List<LineBackground> getLineBackgrounds() {
		return lineBackgrounds;
	}

	// CHECKSTYLE:OFF Generated by eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((lineBackgrounds == null) ? 0 : lineBackgrounds.hashCode());
		result = prime * result + ((styles == null) ? 0 : styles.hashCode());
		return result;
	}
	// CHECKSTYLE:ON Generated by eclipse

	// CHECKSTYLE:OFF Generated by eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		StyleDescription other = (StyleDescription) obj;
		if (lineBackgrounds == null) {
			if (other.lineBackgrounds != null)
				return false;
		} else if (!lineBackgrounds.equals(other.lineBackgrounds))
			return false;
		if (styles == null) {
			if (other.styles != null)
				return false;
		} else if (!styles.equals(other.styles))
			return false;
		return true;
	}
	// CHECKSTYLE:ON Generated by eclipse

}