<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OscalCatalog" nsURI="http://csrc.nist.gov/ns/oscal/1.0/oscal-catalog" nsPrefix="oscal-catalog">
  <eClassifiers xsi:type="ecore:EClass" name="Catalog">
    <eAnnotations source="Metaschema">
      <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>catalog"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;h1>Catalog&lt;/h1>&#xA;&lt;h2>Description&lt;/h2>&#xA;&lt;p>A collection of controls.&lt;/p>&#xA;&lt;h2>Remarks&lt;/h2>&#xA;&lt;p>Catalogs may use one or more &lt;code>group&lt;/code> objects to subdivide the control contents of a catalog.&lt;/p>&#xA;&lt;p>An OSCAL catalog model provides a structured representation of control information.&lt;/p>&#xA;"/>
    </eAnnotations>
    <eSuperTypes href="oscal-metadata.ecore#//OscalElement"/>
    <eSuperTypes href="oscal-metadata.ecore#//UUIDElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backMatter" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-metadata.&lt;AssemblyDefinition>back-matter"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="oscal-metadata.ecore#//BackMatter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1" eType="//Control" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>control"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1" eType="//Group" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" lowerBound="1" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-metadata.&lt;AssemblyDefinition>metadata"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="oscal-metadata.ecore#//Metadata"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog-common.&lt;AssemblyDefinition>parameter"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="oscal-catalog-common.ecore#//Parameter"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control">
    <eAnnotations source="Metaschema">
      <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>control"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;h1>Control&lt;/h1>&#xA;&lt;h2>Description&lt;/h2>&#xA;&lt;p>A structured information object representing a security or privacy control. Each security or privacy control within the Catalog is defined by a distinct control instance.&lt;/p>&#xA;&lt;h2>Remarks&lt;/h2>&#xA;&lt;p>Controls may be grouped using &lt;code>group&lt;/code>, and controls may be partitioned using &lt;code>part&lt;/code> or further enhanced (extended) using &lt;code>control&lt;/code>.&lt;/p>&#xA;"/>
    </eAnnotations>
    <eSuperTypes href="oscal-metadata.ecore#//OscalElement"/>
    <eSuperTypes href="oscal-metadata.ecore#//AnnotationOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//PropertyOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//LinkOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//PartOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//ElementWithClazz"/>
    <eSuperTypes href="oscal-metadata.ecore#//ElementWithId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1" eType="//Control" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>control"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog-common.&lt;AssemblyDefinition>parameter"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="oscal-catalog-common.ecore#//Parameter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>control.&lt;FieldInstance>title"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;h1>Control Title&lt;/h1>&#xA;&lt;h2>Description&lt;/h2>&#xA;&lt;p>A name given to the control, which may be used by a tool for display and navigation.&lt;/p>&#xA;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="oscal-metadata.ecore#//MarkupLineType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Group">
    <eAnnotations source="Metaschema">
      <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>group"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;h1>Control Group&lt;/h1>&#xA;&lt;h2>Description&lt;/h2>&#xA;&lt;p>A group of controls, or of groups of controls.&lt;/p>&#xA;&lt;h2>Remarks&lt;/h2>&#xA;&lt;p>Catalogs can use a &lt;code>group&lt;/code> to collect related controls into a single grouping. That can be useful to group controls into a family or other logical grouping.&lt;/p>&#xA;&lt;p>A &lt;code>group&lt;/code> may have its own properties, statements, parameters, and references, which are inherited by all members of that group.&lt;/p>&#xA;"/>
    </eAnnotations>
    <eSuperTypes href="oscal-metadata.ecore#//OscalElement"/>
    <eSuperTypes href="oscal-metadata.ecore#//AnnotationOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//PropertyOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//LinkOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//PartOwner"/>
    <eSuperTypes href="oscal-metadata.ecore#//ElementWithClazz"/>
    <eSuperTypes href="oscal-metadata.ecore#//ElementWithId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controls" upperBound="-1" eType="//Control" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>control"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1" eType="//Group" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>group"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1" containment="true">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog-common.&lt;AssemblyDefinition>parameter"/>
      </eAnnotations>
      <eType xsi:type="ecore:EClass" href="oscal-catalog-common.ecore#//Parameter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1">
      <eAnnotations source="Metaschema">
        <details key="source" value="&lt;Metaschema>oscal-catalog.&lt;AssemblyDefinition>group.&lt;FieldInstance>title"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;h1>Group Title&lt;/h1>&#xA;&lt;h2>Description&lt;/h2>&#xA;&lt;p>A name given to the group, which may be used by a tool for display and navigation.&lt;/p>&#xA;"/>
      </eAnnotations>
      <eType xsi:type="ecore:EDataType" href="oscal-metadata.ecore#//MarkupLineType"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
